package JuniorsDH.Odontotal.Domain;

public enum Especialidad {
    ESPECIALIDAD_ORTODONCISTA,
    ESPECIALIDAD_PERIODONCISTA,
    ESPECIALIDAD_ENDODONCISTA,
    ESPECIALIDAD_ODONTOPEDIATRIA,
    ESPECIALIDAD_CIRUGIA_ORAL,
    ESPECIALIDAD_CIRUGIA_MAXILOFACIAL,
    ESPECIALIDAD_PROTESISTA
}
