export const routes = {

    Home: "/",
    Service: "/Servicio",
    OurTeam: "/NuestroEquipo",
    AboutUs: "/Conocenos",
    ReserveTurn: "/ReservarTurno",
    MyTurn: "/MisTurnos",
    AddTurnAdmin: "/AgregarTurno",
    ListTurnsAdmin: "/ListaDeTurnos",
    AddDentistAdmin: "/AgregarOdontologo",
    ListDentistAdmin: "/ListaDeOdontologos",
    AddPatientAdmin: "/AgregarPaciente",
    ListPatientAdmin: "/ListaDePacientes",
    AddDentalProsthetist:"/AgregarProtecistas",
    ListDentalProsthetist: "/ListaDeProtecistas",
    Login: "/IniciarSesion",
    Register: "/Registro",
    profile: '/Perfil',
}